site_name: Journy Map Cloud
site_url: https://JournyMapCloud.com/

markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.extra:
    - admonition

remote_branch: gh-pages

theme:
  name: 'readthedocs'
  logo: ''

extra:
  highlightjs: true
  version: master
  feature:
      tabs: true
  palette:
  social:
      - type: github-alt
        link: https://github.com/NULL62d3/JournyMapCloud


copyright: Copyright &copy; NULL62d3

nav:
  - Home: index.md

